name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '2.7' ]
    name: Python ${{ matrix.python }} tests
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Running tox
        run: |
          python -m pip install tox
          tox -e $(tox -ls | grep py$(echo ${{ matrix.python }} | sed 's/\.//') | sed ':1;N;s/\n/,/;t1')
